[package]
name = "dev-reload"
version = "0.1.6"
edition = "2021"

[dependencies]
yew = { version = "0.21" }
gloo-net = { version = "0.6.0", features = ["eventsource"] }
gloo-console = { version = "0.3.0" }
web-sys = { version = "0.3.77" }
futures = { version = "0.3.31" }
gloo-utils = "0.2.0"
